# Generated by Django 4.1.3 on 2022-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sage',
            field=models.BooleanField(default=False),
        ),
    ]
