# Generated by Django 4.1.3 on 2022-11-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_message_name_threads_head_alter_threads_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='threads',
            name='name',
            field=models.CharField(default='Аноним', max_length=20),
        ),
    ]
