# Generated by Django 4.1.3 on 2022-11-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_message_options_alter_threads_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
