# Generated by Django 4.1.3 on 2022-11-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id']},
        ),
    ]
